# Generated by Django 3.1.7 on 2021-03-29 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('cognom', models.TextField(blank=True, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True)),
                ('naixemet', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('ciutat', models.CharField(blank=True, max_length=50, null=True)),
                ('cp', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Llibres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=50, null=True)),
                ('editorial', models.CharField(max_length=50, null=True, verbose_name='Editorial')),
                ('disponible_fisico', models.BooleanField(default=False, verbose_name='Disponible fisico')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llibres', to='bibliotecaApp.autor')),
                ('biblioteca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llibres', to='bibliotecaApp.biblioteca')),
            ],
        ),
        migrations.CreateModel(
            name='Tematica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prestec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('biblioteca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestec', to='bibliotecaApp.biblioteca')),
                ('llibres', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestec', to='bibliotecaApp.llibres')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='llibres',
            name='tematica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llibres', to='bibliotecaApp.tematica'),
        ),
        migrations.AddField(
            model_name='llibres',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
