# Generated by Django 3.1.7 on 2021-03-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestec',
            name='nom',
        ),
        migrations.AddField(
            model_name='prestec',
            name='numEstan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prestec',
            name='numPasillo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prestec',
            name='numPlanta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
